version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 16
    commands:
      - echo "Installing Node.js"
      - npm install
      - echo "Installing AWS CLI"
      - npm install -g aws-cli 
  pre_build:
    commands:
      - aws --version
      - echo "Docker Login"
      - aws ecr get-login-password --region ap-northeast-3 | docker login --username AWS --password-stdin 975050285398.dkr.ecr.ap-northeast-3.amazonaws.com
  build:
    commands: 
      - echo "Docker Build and Push Image!"
      - docker build -t finalproject .
      - docker tag finalproject:latest 975050285398.dkr.ecr.ap-northeast-3.amazonaws.com/finalproject:latest
      - docker push 975050285398.dkr.ecr.ap-northeast-3.amazonaws.com/finalproject:latest
      

artifacts:
  files:
    - '*/'